pipeline {
    agent any

    stages {

        stage('check') {
            steps {
                dir('yet-another-social-media-app') {
                    sh('yet-another-social-media-app/ci.sh')
                }
            }
        }

    }
}